---
name: hinkskalle-dev
kind: pipeline

steps:
- name: fetch
  image: drone/git
  commands:
    - git fetch --tags
    - (git describe || git rev-parse --short HEAD) > .tags
- name: bauhaus
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - >
    docker build
    --label org.label-schema.build-date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    --label org.label-schema.vcs-url="$DRONE_GIT_HTTP_URL"
    --label org.label-schema.vcs-ref="$DRONE_COMMIT_SHA"
    --label at.ac.vcf.ngs.blame="$DRONE_COMMIT_AUTHOR"
    -t ghcr.io/csf-ngs/hinkskalle-dev .
- name: pushraus
  image: docker:dind
  depends_on:
  - bauhaus
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    DOCKER_PASS:
      from_secret: ghcr
    DOCKER_USERNAME:
      from_secret: ghcr-username
  commands:
  - TAG=$(cat .tags)
  - docker tag ghcr.io/csf-ngs/hinkskalle-dev ghcr.io/csf-ngs/hinkskalle-dev:$TAG
  - echo "$DOCKER_PASS" | docker login --username $DOCKER_USERNAME --password-stdin ghcr.io
  - docker push ghcr.io/csf-ngs/hinkskalle-dev
  - docker push ghcr.io/csf-ngs/hinkskalle-dev:$TAG
  when:
    event:
      - tag
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
